language: node_js
node_js:
  - "8.1.3"
install:
  - npm install
script:
  - npm run build
after_deploy:
  - git add build/Countdown.js
  - git add package-lock.json
  - git commit -m "Travis deploy!"
  - git push origin master
deploy:
  api_key: $NPM_TOKEN
  email: thinnakrit.idesign@gmail.com
  provider: npm
  
